POST  http://127.0.0.1:3003/api/v1/users/register
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "test",
  "username": "test",
  "password": "test"
}
###

POST  http://127.0.0.1:3003/api/v1/auth
Content-Type: application/json
  
  {
    "username": "test",
    "password": "test"
  }

###

POST  http://127.0.0.1:3003/api/v1/users/changePassword
Content-Type: application/json

  {
    "JWTtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2NDQ5M2UxOTg5ZWYzNDA1MjI3NDkzYWYiLCJ1c2VybmFtZSI6InRlc3QiLCJ0aW1lc3RhbXAiOiJTdW4gTWF5IDIxIDIwMjMgMTQ6MjU6MDQgR01ULTA0MDAgKEVhc3Rlcm4gRGF5bGlnaHQgVGltZSkiLCJpYXQiOjE2ODM0ODM5MDR9.VyHZVGc_R7jftl47_uGfDtKmBLxQAsIw_bw7ucdUxDQ",
    "oldPassword": "test",
    "newPassword": "test"
  }

###

POST  http://127.0.0.1:3003/api/v1/tickets/create